### ISSUE TITLE
[BUG] Two splits use the same stats_meter

### ISSUE THREAD

**Issue by qinzheng93** [rabbityl/DeformationPyramid#1]
There is a bug [here](https://github.com/rabbityl/DeformationPyramid/blob/842eb2c9e5d26e04813cd39a061c9f02fcc074ce/eval_supervised.py#L71). The `stats_meter` should be set to `None` at the beginning of each split. In the current implementation, the second split will include the results from the first split, i.e., the results on 4DLoMatch-F are much higher the real numbers.

Results after fixing the bug:

| Benchmark   | EPE    | AccS   | AccR   | Outlier |
| :---------: | :----: | :----: | :----: | :-----: |
| 4DMatch-F   | 7.745  | 61.299 | 74.121 | 17.365  |
| 4DLoMatch-F | 17.687 | 26.587 | 41.051 | 33.807  |

The bug mainly affects the results on 4DLoMatch-F, which are much lower than the numbers in the paper.

**Comment by rabbityl** [comment]
Thanks, that's indeed a bug. We will fix and update the paper.

**Comment by rabbityl** [comment]
Thanks for the patience, we fixed the scores in this paper. We managed to increase the scores by replacing the loss from L2 norm to L1 norm, which is more tolerant to large chamfer distance and more robust to correspondence outliers.

**Comment by rabbityl** [comment]
![Untitled](https://user-images.githubusercontent.com/83260553/194217585-0a6736b4-fb6e-4328-935d-d02e3cb2c584.jpg)
