### ISSUE TITLE
name 'i' is not define.

### ISSUE THREAD

**Issue by Leestronger** [rabbityl/DeformationPyramid#11]
Hello!When I run
 `python eval_nolearned.py --config config/NDP.yaml --visualize`,
I got this error: 
```
File "eval_nolearned.py", line 148, in <module>
message = f'{i}/{len(D)}:'
NameError: name 'i' is not defined
```
https://github.com/rabbityl/DeformationPyramid/blob/b388363413f657e27bf7181c21ac48bbb40a80f6/eval_nolearned.py#L148
Is i is the index of the loop? Which should be put into circulate.https://github.com/rabbityl/DeformationPyramid/blob/cd224324e0beb178e4d2ebf1524008e44ae77ea8/eval_nolearned.py#L70

but when I put [this](https://github.com/rabbityl/DeformationPyramid/blob/cd224324e0beb178e4d2ebf1524008e44ae77ea8/eval_nolearned.py#L147-152) into circulate, it becomes to this 
![image](https://user-images.githubusercontent.com/118326553/229518871-54304333-8715-4a55-aa75-3bb5625aa719.png)

**Comment by balabalaboy** [comment]
ok I reset the soft link of the dataset, it seems right
the structure of the data folder should be as below：
![image](https://user-images.githubusercontent.com/125865806/230004913-e640b338-9c7f-414f-88ab-fdfcdfb0d564.png)
My previous file structure was set to look like this

- data
   - 4DLoMatch-F
   - 4DMatch-F
   - train
   - val

**Comment by Leestronger** [comment]
ok I reset the soft link of the dataset, it seems right
the structure of the data folder should be as below：
```
|-- data
    |-- split
         |-- 4DLoMatch-F
         |-- 4DMatch-F
         |-- train
         |-- val 
```
My previous file structure was set to look like this
```
|-- data
     |-- 4DLoMatch-F
     |-- 4DMatch-F
     |-- train
     |-- val 
```

**Comment by eashratj** [comment]
hi! I am having the similar issue and I have put the loop into circulate and my data structure seems to be correct but the issue still persists.. do you have any suggestion? 
![pyramid](https://github.com/rabbityl/DeformationPyramid/assets/97810581/5c088930-7fb8-4041-b039-2758322dc938)

**Comment by OzgurMertEmir** [comment]
Hello,
I am working on google colab and despite having the same folder structure @Leestronger mentioned, I am still getting the error: name 'i' is not defined.

/content/DeformationPyramid# python eval_nolearned.py --config config/NDP.yaml  
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/content/DeformationPyramid/eval_nolearned.py", line 148, in <module>
    message = f'{i}/{len(D)}: '
NameError: name 'i' is not defined. Did you mean: 'id'?

I suspected that it might be an indentation error and try to indent that part of the code ( eval_nolearned.py:[148,152] ). 
However that also did not work. 

Result:
/content/DeformationPyramid# python eval_nolearned.py --config config/NDP.yaml  
0it [00:00, ?it/s]
0it [00:00, ?it/s]
time cost average

I would really appreciate any help/guidance on this issue.
