### ISSUE TITLE
NameError: name 'SamplesLoss' is not defined

### ISSUE THREAD

**Issue by zikai1** [rabbityl/DeformationPyramid#15]
Hi, 

Thank you for this great work! When I ran the **demo.py** about the **"Sinkhorn"** registration:

![f12fcab2c916648735c42443638e6ce](https://github.com/rabbityl/DeformationPyramid/assets/37583980/ca6e6db4-7c5b-4656-ba40-de3c2dec6623)

The following error emerges:
![1696811376021](https://github.com/rabbityl/DeformationPyramid/assets/37583980/3de109c9-922f-4155-be56-9f09605c2db4)

Could you please provide the **SampleLoss file**? Thank you very much in advance.

**Comment by rabbityl** [comment]
Change the line-9 to True `Runbaselines=False`, and make sure geomloss is installed.

**Comment by zikai1** [comment]
> Change the line-9 to True `Runbaselines=False`, and make sure geomloss is installed.

Thank you!
