### ISSUE TITLE
The following error is prompted when downloading MVRegC

### ISSUE THREAD

**Issue by Huaixv17** [rabbityl/DeformationPyramid#2]
I prompted the error after entering “python setup.py build” under the DeformationPyramid-main\cxx folder

LINK : fatal error LNK1181: The input file cannot be opened “C:\Users\Administrator\DeformationPyramid-main\cxx\build\temp.win-amd64-cpython-39\Release\Users\Administrator\DeformationPyramid-main\cxx\.\cpu\graph_proc.obj”

**Comment by rabbityl** [comment]
Run `python setup.py install`

**Comment by rabbityl** [comment]
It is not necessary to install MVgC, as it is a lib for a baseline method (N-ICP).
I just removed it from the import in [here](https://github.com/rabbityl/DeformationPyramid/blob/main/model/geometry.py#L3).
