### ISSUE TITLE
Could you please provide a demo.py

### ISSUE THREAD

**Issue by simba611** [rabbityl/DeformationPyramid#3]
Could you please provide a demo.py which takes source and target pointclouds as inputs and outputs the transformations and the warped source ?

**Comment by rabbityl** [comment]
It is already there:
`python shape_transfer.py -s sim3_demo/AlienSoldier.ply -t sim3_demo/Ortiz.ply`

**Comment by simba611** [comment]
Thanks, could you please also clarify how to switch between using lepard based correspondences vs non learning based correspondences in that file ?

**Comment by rabbityl** [comment]
Current shape transfer only run in no-learned setting.
You can refer to eval_supervised.py for how to integrate correspondence.

**Comment by 1215232494** [comment]
> 

Could you give me some hints? The data formats received by both are not the same, I don't have any idea how to implement it
