### ISSUE TITLE
When I run the NDP sample, the following scenario occurs, and the dataset is present

### ISSUE THREAD

**Issue by Huaixv17** [rabbityl/DeformationPyramid#4]
![图片1](https://user-images.githubusercontent.com/92208251/183562950-47ee2f36-c249-400c-930c-332d58882f1e.png)

**Comment by rabbityl** [comment]
It seems that the data is not properly loaded.

**Comment by Leestronger** [comment]
> ![图片1](https://user-images.githubusercontent.com/92208251/183562950-47ee2f36-c249-400c-930c-332d58882f1e.png)

I meet the same problem ,do you fix it?

**Comment by Huaixv17** [comment]
This is because the path of the dataset is wrong, modify the data root in the corresponding yaml file to solve.

**Comment by Leestronger** [comment]
> This is because the path of the dataset is wrong, modify the data root in the corresponding yaml file to solve.

thank you so much! yes I found this mistake , I made a mistake in the file hierarchy.
