### ISSUE TITLE
About the significance of low-overlap non-rigid point cloud registration

### ISSUE THREAD

**Issue by Huaixv17** [rabbityl/DeformationPyramid#5]
Thank you for your work. It inspired me a lot.

But I don't quite understand the significance of low-overlap non-rigid point cloud registration when the source point cloud does not fully contain the target point cloud. 

For example, in the case of only a small part of the overlap between the two point clouds in 4dLoMatch, most of the points cannot find the corresponding point at all, so what is the significance of this non-rigid low-overlap point cloud registration?

**Comment by rabbityl** [comment]
Partial registration is a core component for monocular reconstruction: i.e. each frame/pCloud only has partial observation of the scenes, by accumulating low-overlapping observations you get a complete reconstruction of the scenes.

**Comment by Huaixv17** [comment]
But why should points that exist in the source point cloud but do not exist in the target point cloud also be registered？Shouldn't the purpose of registration be to register the corresponding points that exist in both point clouds?
