### ISSUE TITLE
But why should points that exist in the source point cloud but do not exist in the target point cloud also be registered？Shouldn't the purpose of registration be to register the corresponding points that exist in both point clouds?

### ISSUE THREAD

**Issue by Huaixv17** [rabbityl/DeformationPyramid#6]
But why should points that exist in the source point cloud but do not exist in the target point cloud also be registered？Shouldn't the purpose of registration be to register the corresponding points that exist in both point clouds?

_Originally posted by @Huaixv17 in https://github.com/rabbityl/DeformationPyramid/issues/5#issuecomment-1264515294_

**Comment by rabbityl** [comment]
Please note the definition of registration: you need to transform all points from source to target, even if a point does not have any correspondence.
