### ISSUE TITLE
Training DeformationPyramid

### ISSUE THREAD

**Issue by aiday-mar** [rabbityl/DeformationPyramid#7]
Hi,

I am currently training the DeformationPyramid network by running the main.py file under the correspondence folder. The _snapshot function saves one set of weights. I noticed, however, that during testing the code refers to two different sets of weights: weights for the Lepard network and for the OutlierRejection network. Do the weights saved by the _snapshot correspond to the first, second network or both? Perhaps if the weights returned correspond to one of the networks only, there is code to train the second network? Thank you for the help.

**Comment by rabbityl** [comment]
The weights contains both two networks.
In this project, we only train the OutlierRejection network, while using the pre-trained Lepard. 

To train OutlierRejection, run

```
cd correspondence
python main.py configs/train/4dmatch.yaml
```

**Comment by supersyq** [comment]
Hi, 
Thank you for sharing this wonderful project. And I am training the DeformationPyramid network, but I find that one epoch training costs about 3 hours with a batch size of 4 on a Geforce RTX 2080Ti GPU. How long does it take for network training to converge?

**Comment by rabbityl** [comment]
I remember it took less than 1 day on my GPU (Nvidia A100), about 15 epoches till convergence.

**Comment by aiday-mar** [comment]
Thanks for the reply. I'll then train the Lepard network individualy from the following repo: https://github.com/rabbityl/lepard. Then use the weights obtained in NDP.
